In [2]:
#!conda install --name root scikit-learn -y

In [3]:
#!conda install --name root -c conda-forge tensorflow -y

In [4]:
#!conda install --name root keras -y

In [5]:
import numpy as np

from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM

Using TensorFlow backend.


In [6]:
leng=4

data = [[i+j for j in range(leng)] for i in range(100)]
data = np.array(data, dtype=np.float32)
target = [[i+j+1 for j in range(leng)] for i in range(100)]
target = np.array(target, dtype=np.float32)
print(data[:10])
print(target[:10])
data = data.reshape(100, 1, leng)/200
target = target.reshape(100,1,leng)/200

[[  0.   1.   2.   3.]
 [  1.   2.   3.   4.]
 [  2.   3.   4.   5.]
 [  3.   4.   5.   6.]
 [  4.   5.   6.   7.]
 [  5.   6.   7.   8.]
 [  6.   7.   8.   9.]
 [  7.   8.   9.  10.]
 [  8.   9.  10.  11.]
 [  9.  10.  11.  12.]]
[[  1.   2.   3.   4.]
 [  2.   3.   4.   5.]
 [  3.   4.   5.   6.]
 [  4.   5.   6.   7.]
 [  5.   6.   7.   8.]
 [  6.   7.   8.   9.]
 [  7.   8.   9.  10.]
 [  8.   9.  10.  11.]
 [  9.  10.  11.  12.]
 [ 10.  11.  12.  13.]]


In [ ]:

model = Sequential()  
model.add(LSTM(leng, input_shape=(1, leng),return_sequences=True,activation='sigmoid'))
model.add(LSTM(leng, input_shape=(1, leng),return_sequences=True,activation='sigmoid'))
model.add(LSTM(leng, input_shape=(1, leng),return_sequences=True,activation='sigmoid'))
model.add(LSTM(leng, input_shape=(1, leng),return_sequences=True,activation='sigmoid'))
model.add(LSTM(leng, input_shape=(1, leng),return_sequences=True,activation='sigmoid'))
model.add(LSTM(leng, input_shape=(1, leng),return_sequences=True,activation='sigmoid'))

In [ ]:
model.compile(loss='mse', optimizer='adam',metrics=['accuracy'])
model.fit(data, target, epochs=10000, batch_size=50,validation_data=(data,target))

Train on 100 samples, validate on 100 samples
Epoch 1/10000
100/100 [==============================] - 12s 120ms/step - loss: 0.0226 - acc: 0.0000e+00 - val_loss: 0.0226 - val_acc: 0.0000e+00
Epoch 2/10000
100/100 [==============================] - 0s 326us/step - loss: 0.0226 - acc: 0.0000e+00 - val_loss: 0.0226 - val_acc: 0.0000e+00
Epoch 3/10000
100/100 [==============================] - 0s 266us/step - loss: 0.0226 - acc: 0.0000e+00 - val_loss: 0.0225 - val_acc: 0.0000e+00
Epoch 4/10000
100/100 [==============================] - 0s 231us/step - loss: 0.0225 - acc: 0.0000e+00 - val_loss: 0.0225 - val_acc: 0.0000e+00
Epoch 5/10000
100/100 [==============================] - 0s 466us/step - loss: 0.0225 - acc: 0.0000e+00 - val_loss: 0.0225 - val_acc: 0.0000e+00
Epoch 6/10000
100/100 [========================

In [ ]:
predict = model.predict(data)

In [ ]:
print(predict)