In [8]:
!conda install --name root scikit-learn -y

Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/nbcommon/anaconda3_431:

The following NEW packages will be INSTALLED:

    intel-openmp: 2018.0.0-h15fc484_7                      
    libgcc-ng:    7.2.0-hcbc56d2_1                         
    libstdcxx-ng: 7.2.0-h24385c6_1                         

The following packages will be UPDATED:

    mkl:          2017.0.1-0                                --> 2018.0.0-hb491cac_4  
    numexpr:      2.6.1-np111py36_2                         --> 2.6.2-py36hdd3393f_1 

The following packages will be SUPERSEDED by a higher-priority channel:

    scikit-learn: 0.19.0-py36_blas_openblas_201 conda-forge [blas_openblas] --> 0.19.0-py36h97ac459_2

intel-openmp-2 100% |################################| Time: 0:00:00   5.55 MB/s
libgcc-ng-7.2. 100% |################################| Time: 0:00:00  18.86 MB/s
libstdcxx-ng-7 100% |################################| Time: 0:00:00  2

In [2]:
!conda install --name root -c conda-forge tensorflow -y

Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /home/nbcommon/anaconda3_431:

The following NEW packages will be INSTALLED:

    mock:         2.0.0-py36_0          conda-forge
    pbr:          3.1.1-py36_0          conda-forge

The following packages will be UPDATED:

    scikit-learn: 0.18.1-np111py36_1                --> 0.19.0-py36_blas_openblas_201 conda-forge [blas_openblas]

The following packages will be SUPERSEDED by a higher-priority channel:

    conda:        4.3.27-py36h2866c0b_0             --> 4.3.27-py36_0                 conda-forge
    conda-env:    2.6.0-0                           --> 2.6.0-0                       conda-forge
    tensorflow:   1.3.0-0                           --> 1.3.0-py36_0                  conda-forge

conda-env-2.6. 100% |################################| Time: 0:00:00 917.14 kB/s
pbr-3.1.1-py36 100% |################################| Time: 0:00:00 830.54 kB/s
mock-2.0.0-

In [3]:
!conda install --name root keras -y

Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/nbcommon/anaconda3_431:

The following packages will be UPDATED:

    conda-env: 2.6.0-0       conda-forge --> 2.6.0-h36134e3_1     

The following packages will be SUPERSEDED by a higher-priority channel:

    conda:     4.3.27-py36_0 conda-forge --> 4.3.27-py36h2866c0b_0

conda-env-2.6. 100% |################################| Time: 0:00:00   3.02 MB/s


In [2]:
import numpy as np

from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM

In [7]:
leng=4

data = [[i+j for j in range(leng)] for i in range(100)]
data = np.array(data, dtype=np.float32)
target = [[i+j+1 for j in range(leng)] for i in range(100)]
target = np.array(target, dtype=np.float32)
print(data[:10])
print(target[:10])
data = data.reshape(100, 1, leng)/200
target = target.reshape(100,1,leng)/200

[[  0.   1.   2.   3.]
 [  1.   2.   3.   4.]
 [  2.   3.   4.   5.]
 [  3.   4.   5.   6.]
 [  4.   5.   6.   7.]
 [  5.   6.   7.   8.]
 [  6.   7.   8.   9.]
 [  7.   8.   9.  10.]
 [  8.   9.  10.  11.]
 [  9.  10.  11.  12.]]
[[  1.   2.   3.   4.]
 [  2.   3.   4.   5.]
 [  3.   4.   5.   6.]
 [  4.   5.   6.   7.]
 [  5.   6.   7.   8.]
 [  6.   7.   8.   9.]
 [  7.   8.   9.  10.]
 [  8.   9.  10.  11.]
 [  9.  10.  11.  12.]
 [ 10.  11.  12.  13.]]


In [ ]:

model = Sequential()  
model.add(LSTM(leng, input_shape=(1, leng),return_sequences=True,activation='sigmoid'))
model.add(LSTM(leng, input_shape=(1, leng),return_sequences=True,activation='sigmoid'))
model.add(LSTM(leng, input_shape=(1, leng),return_sequences=True,activation='sigmoid'))
model.add(LSTM(leng, input_shape=(1, leng),return_sequences=True,activation='sigmoid'))
model.add(LSTM(leng, input_shape=(1, leng),return_sequences=True,activation='sigmoid'))
model.add(LSTM(leng, input_shape=(1, leng),return_sequences=True,activation='sigmoid'))

In [ ]:
model.compile(loss='mse', optimizer='adam',metrics=['accuracy'])
model.fit(data, target, epochs=10000, batch_size=50,validation_data=(data,target))

Train on 100 samples, validate on 100 samples
Epoch 1/10000
100/100 [==============================] - 0s - loss: 0.0216 - acc: 0.0000e+00 - val_loss: 0.0215 - val_acc: 0.0000e+00
Epoch 2/10000
100/100 [==============================] - 0s - loss: 0.0215 - acc: 0.0000e+00 - val_loss: 0.0215 - val_acc: 0.0000e+00
Epoch 3/10000
100/100 [==============================] - 0s - loss: 0.0215 - acc: 0.0000e+00 - val_loss: 0.0215 - val_acc: 0.0000e+00
Epoch 4/10000
100/100 [==============================] - 0s - loss: 0.0215 - acc: 0.0000e+00 - val_loss: 0.0215 - val_acc: 0.0000e+00
Epoch 5/10000
100/100 [==============================] - 0s - loss: 0.0215 - acc: 0.0000e+00 - val_loss: 0.0214 - val_acc: 0.0000e+00
Epoch 6/10000
100/100 [==============================] - 0s - loss: 0.0214 - acc: 0.0000e+00 - val_loss: 0.0214 - val_acc: 0.0000e+00
Epoch 7/10000
100/100 [==============================] - 0s - loss: 0.0214 - acc: 0.0000e+00 - val_loss: 0.0214 - val_acc: 0.0000e+00
Epoch 8/10000
10

100/100 [==============================] - 0s - loss: 0.0209 - acc: 0.0000e+00 - val_loss: 0.0209 - val_acc: 0.0000e+00
Epoch 62/10000
100/100 [==============================] - 0s - loss: 0.0209 - acc: 0.0000e+00 - val_loss: 0.0209 - val_acc: 0.0000e+00
Epoch 63/10000
100/100 [==============================] - 0s - loss: 0.0209 - acc: 0.0000e+00 - val_loss: 0.0209 - val_acc: 0.0000e+00
Epoch 64/10000
100/100 [==============================] - 0s - loss: 0.0209 - acc: 0.0000e+00 - val_loss: 0.0209 - val_acc: 0.0000e+00
Epoch 65/10000
100/100 [==============================] - 0s - loss: 0.0209 - acc: 0.0000e+00 - val_loss: 0.0209 - val_acc: 0.0000e+00
Epoch 66/10000
100/100 [==============================] - 0s - loss: 0.0209 - acc: 0.0000e+00 - val_loss: 0.0209 - val_acc: 0.0000e+00
Epoch 67/10000
100/100 [==============================] - 0s - loss: 0.0209 - acc: 0.0000e+00 - val_loss: 0.0209 - val_acc: 0.0000e+00
Epoch 68/10000
100/100 [==============================] - 0s - loss: 0

100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 266/10000
100/100 [==============================] - ETA: 0s - loss: 0.0205 - acc: 1.000 - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 267/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 268/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 269/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 270/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 271/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 272/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc

100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 393/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 394/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 395/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 396/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 397/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 398/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 399/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc:

100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 521/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 522/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 523/10000
100/100 [==============================] - ETA: 0s - loss: 0.0216 - acc: 1.000 - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 524/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 525/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 526/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 527/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc

100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 648/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 649/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 650/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 651/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 652/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 653/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 654/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc:

100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 776/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 777/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 778/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 779/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 780/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 781/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 782/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc:

100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 903/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 904/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 905/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 906/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 907/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 908/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 909/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc:

100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1029/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1030/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1031/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1032/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1033/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1034/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1035/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - v

100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1155/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1156/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1157/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1158/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1159/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1160/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1161/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - v

100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1281/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1282/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1283/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1284/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1285/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1286/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1287/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - v

100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1407/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1408/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1409/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1410/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1411/10000
100/100 [==============================] - ETA: 0s - loss: 0.0226 - acc: 1.000 - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1412/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1413/10000
100/100 [==============================] - 0s - loss: 0.020

100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1532/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1533/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1534/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1535/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1536/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1537/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1538/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - v

100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1658/10000
100/100 [==============================] - ETA: 0s - loss: 0.0191 - acc: 1.000 - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1659/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1660/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1661/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1662/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1663/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1664/10000
100/100 [==============================] - ETA: 0s - loss: 

100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1783/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1784/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1785/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1786/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1787/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1788/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1789/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - v

100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1909/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1910/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1911/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1912/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1913/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1914/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1915/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - v

100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1972/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1973/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1974/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1975/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1976/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1977/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 1978/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - v

100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 2098/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 2099/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 2100/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 2101/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 2102/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 2103/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 2104/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - v

100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 2223/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 2224/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 2225/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 2226/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 2227/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 2228/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 2229/10000
100/100 [==============================] - 0s - loss: 0.0208 - acc: 1.0000 - val_loss: 0.0208 - v

100/100 [==============================] - 0s - loss: 0.0188 - acc: 0.6300 - val_loss: 0.0187 - val_acc: 0.6300
Epoch 2349/10000
100/100 [==============================] - 0s - loss: 0.0187 - acc: 0.6300 - val_loss: 0.0186 - val_acc: 0.6300
Epoch 2350/10000
100/100 [==============================] - 0s - loss: 0.0186 - acc: 0.6200 - val_loss: 0.0186 - val_acc: 0.6200
Epoch 2351/10000
100/100 [==============================] - 0s - loss: 0.0186 - acc: 0.6200 - val_loss: 0.0185 - val_acc: 0.6200
Epoch 2352/10000
100/100 [==============================] - 0s - loss: 0.0185 - acc: 0.6200 - val_loss: 0.0185 - val_acc: 0.6100
Epoch 2353/10000
100/100 [==============================] - 0s - loss: 0.0185 - acc: 0.6100 - val_loss: 0.0184 - val_acc: 0.6100
Epoch 2354/10000
100/100 [==============================] - 0s - loss: 0.0184 - acc: 0.6100 - val_loss: 0.0183 - val_acc: 0.6000
Epoch 2355/10000
100/100 [==============================] - 0s - loss: 0.0183 - acc: 0.6000 - val_loss: 0.0183 - v

100/100 [==============================] - 0s - loss: 0.0057 - acc: 0.5600 - val_loss: 0.0057 - val_acc: 0.5600
Epoch 2475/10000
100/100 [==============================] - 0s - loss: 0.0056 - acc: 0.5600 - val_loss: 0.0056 - val_acc: 0.5600
Epoch 2476/10000
100/100 [==============================] - 0s - loss: 0.0056 - acc: 0.5600 - val_loss: 0.0055 - val_acc: 0.5600
Epoch 2477/10000
100/100 [==============================] - 0s - loss: 0.0055 - acc: 0.5600 - val_loss: 0.0055 - val_acc: 0.5600
Epoch 2478/10000
100/100 [==============================] - 0s - loss: 0.0054 - acc: 0.5600 - val_loss: 0.0054 - val_acc: 0.5600
Epoch 2479/10000
100/100 [==============================] - 0s - loss: 0.0054 - acc: 0.5600 - val_loss: 0.0053 - val_acc: 0.5600
Epoch 2480/10000
100/100 [==============================] - 0s - loss: 0.0053 - acc: 0.5600 - val_loss: 0.0053 - val_acc: 0.5600
Epoch 2481/10000
100/100 [==============================] - 0s - loss: 0.0052 - acc: 0.5600 - val_loss: 0.0052 - v

100/100 [==============================] - 0s - loss: 0.0014 - acc: 0.6500 - val_loss: 0.0014 - val_acc: 0.6500
Epoch 2601/10000
100/100 [==============================] - 0s - loss: 0.0014 - acc: 0.6500 - val_loss: 0.0014 - val_acc: 0.6500
Epoch 2602/10000
100/100 [==============================] - 0s - loss: 0.0014 - acc: 0.6500 - val_loss: 0.0014 - val_acc: 0.6500
Epoch 2603/10000
100/100 [==============================] - 0s - loss: 0.0014 - acc: 0.6600 - val_loss: 0.0014 - val_acc: 0.6600
Epoch 2604/10000
100/100 [==============================] - 0s - loss: 0.0014 - acc: 0.6600 - val_loss: 0.0014 - val_acc: 0.6600
Epoch 2605/10000
100/100 [==============================] - 0s - loss: 0.0014 - acc: 0.6600 - val_loss: 0.0014 - val_acc: 0.6600
Epoch 2606/10000
100/100 [==============================] - 0s - loss: 0.0014 - acc: 0.6600 - val_loss: 0.0014 - val_acc: 0.6600
Epoch 2607/10000
100/100 [==============================] - 0s - loss: 0.0014 - acc: 0.6600 - val_loss: 0.0013 - v

100/100 [==============================] - 0s - loss: 4.9992e-04 - acc: 0.7600 - val_loss: 4.9681e-04 - val_acc: 0.7600
Epoch 2722/10000
100/100 [==============================] - 0s - loss: 4.9572e-04 - acc: 0.7600 - val_loss: 4.9280e-04 - val_acc: 0.7600
Epoch 2723/10000
100/100 [==============================] - 0s - loss: 4.9188e-04 - acc: 0.7600 - val_loss: 4.8884e-04 - val_acc: 0.7600
Epoch 2724/10000
100/100 [==============================] - 0s - loss: 4.8802e-04 - acc: 0.7600 - val_loss: 4.8491e-04 - val_acc: 0.7600
Epoch 2725/10000
100/100 [==============================] - 0s - loss: 4.8390e-04 - acc: 0.7600 - val_loss: 4.8102e-04 - val_acc: 0.7600
Epoch 2726/10000
100/100 [==============================] - 0s - loss: 4.8011e-04 - acc: 0.7600 - val_loss: 4.7719e-04 - val_acc: 0.7600
Epoch 2727/10000
100/100 [==============================] - 0s - loss: 4.7616e-04 - acc: 0.7600 - val_loss: 4.7336e-04 - val_acc: 0.7600
Epoch 2728/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 2.0806e-04 - acc: 0.8300 - val_loss: 2.0694e-04 - val_acc: 0.8300
Epoch 2840/10000
100/100 [==============================] - 0s - loss: 2.0663e-04 - acc: 0.8300 - val_loss: 2.0555e-04 - val_acc: 0.8300
Epoch 2841/10000
100/100 [==============================] - 0s - loss: 2.0530e-04 - acc: 0.8300 - val_loss: 2.0414e-04 - val_acc: 0.8400
Epoch 2842/10000
100/100 [==============================] - 0s - loss: 2.0387e-04 - acc: 0.8400 - val_loss: 2.0276e-04 - val_acc: 0.8400
Epoch 2843/10000
100/100 [==============================] - 0s - loss: 2.0242e-04 - acc: 0.8400 - val_loss: 2.0139e-04 - val_acc: 0.8400
Epoch 2844/10000
100/100 [==============================] - 0s - loss: 2.0104e-04 - acc: 0.8400 - val_loss: 2.0007e-04 - val_acc: 0.8400
Epoch 2845/10000
100/100 [==============================] - 0s - loss: 1.9969e-04 - acc: 0.8400 - val_loss: 1.9872e-04 - val_acc: 0.8400
Epoch 2846/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 9.9231e-05 - acc: 0.9000 - val_loss: 9.8783e-05 - val_acc: 0.9000
Epoch 2958/10000
100/100 [==============================] - 0s - loss: 9.8646e-05 - acc: 0.9000 - val_loss: 9.8217e-05 - val_acc: 0.9000
Epoch 2959/10000
100/100 [==============================] - 0s - loss: 9.8069e-05 - acc: 0.9000 - val_loss: 9.7654e-05 - val_acc: 0.9000
Epoch 2960/10000
100/100 [==============================] - 0s - loss: 9.7564e-05 - acc: 0.9000 - val_loss: 9.7087e-05 - val_acc: 0.9000
Epoch 2961/10000
100/100 [==============================] - 0s - loss: 9.7002e-05 - acc: 0.9000 - val_loss: 9.6528e-05 - val_acc: 0.9000
Epoch 2962/10000
100/100 [==============================] - 0s - loss: 9.6373e-05 - acc: 0.9000 - val_loss: 9.5985e-05 - val_acc: 0.9000
Epoch 2963/10000
100/100 [==============================] - 0s - loss: 9.5883e-05 - acc: 0.9000 - val_loss: 9.5442e-05 - val_acc: 0.9000
Epoch 2964/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 5.3758e-05 - acc: 1.0000 - val_loss: 5.3576e-05 - val_acc: 1.0000
Epoch 3076/10000
100/100 [==============================] - 0s - loss: 5.3545e-05 - acc: 1.0000 - val_loss: 5.3286e-05 - val_acc: 1.0000
Epoch 3077/10000
100/100 [==============================] - 0s - loss: 5.3228e-05 - acc: 1.0000 - val_loss: 5.3072e-05 - val_acc: 1.0000
Epoch 3078/10000
100/100 [==============================] - 0s - loss: 5.3023e-05 - acc: 1.0000 - val_loss: 5.2841e-05 - val_acc: 1.0000
Epoch 3079/10000
100/100 [==============================] - 0s - loss: 5.2820e-05 - acc: 1.0000 - val_loss: 5.2598e-05 - val_acc: 1.0000
Epoch 3080/10000
100/100 [==============================] - 0s - loss: 5.2528e-05 - acc: 1.0000 - val_loss: 5.2376e-05 - val_acc: 1.0000
Epoch 3081/10000
100/100 [==============================] - 0s - loss: 5.2342e-05 - acc: 1.0000 - val_loss: 5.2165e-05 - val_acc: 1.0000
Epoch 3082/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 3.3147e-05 - acc: 1.0000 - val_loss: 3.3062e-05 - val_acc: 1.0000
Epoch 3194/10000
100/100 [==============================] - 0s - loss: 3.3038e-05 - acc: 1.0000 - val_loss: 3.2938e-05 - val_acc: 1.0000
Epoch 3195/10000
100/100 [==============================] - 0s - loss: 3.2923e-05 - acc: 1.0000 - val_loss: 3.2817e-05 - val_acc: 1.0000
Epoch 3196/10000
100/100 [==============================] - 0s - loss: 3.2778e-05 - acc: 1.0000 - val_loss: 3.2705e-05 - val_acc: 1.0000
Epoch 3197/10000
100/100 [==============================] - 0s - loss: 3.2745e-05 - acc: 1.0000 - val_loss: 3.2609e-05 - val_acc: 1.0000
Epoch 3198/10000
100/100 [==============================] - 0s - loss: 3.2601e-05 - acc: 1.0000 - val_loss: 3.2463e-05 - val_acc: 1.0000
Epoch 3199/10000
100/100 [==============================] - 0s - loss: 3.2498e-05 - acc: 1.0000 - val_loss: 3.2358e-05 - val_acc: 1.0000
Epoch 3200/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 2.1560e-05 - acc: 1.0000 - val_loss: 2.1509e-05 - val_acc: 1.0000
Epoch 3312/10000
100/100 [==============================] - 0s - loss: 2.1492e-05 - acc: 1.0000 - val_loss: 2.1409e-05 - val_acc: 1.0000
Epoch 3313/10000
100/100 [==============================] - 0s - loss: 2.1406e-05 - acc: 1.0000 - val_loss: 2.1335e-05 - val_acc: 1.0000
Epoch 3314/10000
100/100 [==============================] - 0s - loss: 2.1326e-05 - acc: 1.0000 - val_loss: 2.1260e-05 - val_acc: 1.0000
Epoch 3315/10000
100/100 [==============================] - 0s - loss: 2.1238e-05 - acc: 1.0000 - val_loss: 2.1181e-05 - val_acc: 1.0000
Epoch 3316/10000
100/100 [==============================] - 0s - loss: 2.1157e-05 - acc: 1.0000 - val_loss: 2.1110e-05 - val_acc: 1.0000
Epoch 3317/10000
100/100 [==============================] - 0s - loss: 2.1119e-05 - acc: 1.0000 - val_loss: 2.1034e-05 - val_acc: 1.0000
Epoch 3318/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 1.4759e-05 - acc: 1.0000 - val_loss: 1.4723e-05 - val_acc: 1.0000
Epoch 3430/10000
100/100 [==============================] - 0s - loss: 1.4708e-05 - acc: 1.0000 - val_loss: 1.4678e-05 - val_acc: 1.0000
Epoch 3431/10000
100/100 [==============================] - 0s - loss: 1.4711e-05 - acc: 1.0000 - val_loss: 1.4636e-05 - val_acc: 1.0000
Epoch 3432/10000
100/100 [==============================] - 0s - loss: 1.4643e-05 - acc: 1.0000 - val_loss: 1.4592e-05 - val_acc: 1.0000
Epoch 3433/10000
100/100 [==============================] - 0s - loss: 1.4594e-05 - acc: 1.0000 - val_loss: 1.4545e-05 - val_acc: 1.0000
Epoch 3434/10000
100/100 [==============================] - 0s - loss: 1.4560e-05 - acc: 1.0000 - val_loss: 1.4513e-05 - val_acc: 1.0000
Epoch 3435/10000
100/100 [==============================] - 0s - loss: 1.4514e-05 - acc: 1.0000 - val_loss: 1.4469e-05 - val_acc: 1.0000
Epoch 3436/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 1.0374e-05 - acc: 1.0000 - val_loss: 1.0346e-05 - val_acc: 1.0000
Epoch 3548/10000
100/100 [==============================] - 0s - loss: 1.0347e-05 - acc: 1.0000 - val_loss: 1.0326e-05 - val_acc: 1.0000
Epoch 3549/10000
100/100 [==============================] - 0s - loss: 1.0331e-05 - acc: 1.0000 - val_loss: 1.0291e-05 - val_acc: 1.0000
Epoch 3550/10000
100/100 [==============================] - 0s - loss: 1.0274e-05 - acc: 1.0000 - val_loss: 1.0260e-05 - val_acc: 1.0000
Epoch 3551/10000
100/100 [==============================] - 0s - loss: 1.0253e-05 - acc: 1.0000 - val_loss: 1.0239e-05 - val_acc: 1.0000
Epoch 3552/10000
100/100 [==============================] - 0s - loss: 1.0252e-05 - acc: 1.0000 - val_loss: 1.0215e-05 - val_acc: 1.0000
Epoch 3553/10000
100/100 [==============================] - 0s - loss: 1.0203e-05 - acc: 1.0000 - val_loss: 1.0174e-05 - val_acc: 1.0000
Epoch 3554/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 7.6646e-06 - acc: 1.0000 - val_loss: 7.5896e-06 - val_acc: 1.0000
Epoch 3666/10000
100/100 [==============================] - 0s - loss: 7.5798e-06 - acc: 1.0000 - val_loss: 7.5451e-06 - val_acc: 1.0000
Epoch 3667/10000
100/100 [==============================] - 0s - loss: 7.5500e-06 - acc: 1.0000 - val_loss: 7.5284e-06 - val_acc: 1.0000
Epoch 3668/10000
100/100 [==============================] - 0s - loss: 7.5556e-06 - acc: 1.0000 - val_loss: 7.5252e-06 - val_acc: 1.0000
Epoch 3669/10000
100/100 [==============================] - 0s - loss: 7.5125e-06 - acc: 1.0000 - val_loss: 7.4848e-06 - val_acc: 1.0000
Epoch 3670/10000
100/100 [==============================] - 0s - loss: 7.4930e-06 - acc: 1.0000 - val_loss: 7.4796e-06 - val_acc: 1.0000
Epoch 3671/10000
100/100 [==============================] - 0s - loss: 7.4806e-06 - acc: 1.0000 - val_loss: 7.4502e-06 - val_acc: 1.0000
Epoch 3672/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 5.7058e-06 - acc: 1.0000 - val_loss: 5.6933e-06 - val_acc: 1.0000
Epoch 3783/10000
100/100 [==============================] - 0s - loss: 5.7082e-06 - acc: 1.0000 - val_loss: 5.6666e-06 - val_acc: 1.0000
Epoch 3784/10000
100/100 [==============================] - 0s - loss: 5.6853e-06 - acc: 1.0000 - val_loss: 5.6815e-06 - val_acc: 1.0000
Epoch 3785/10000
100/100 [==============================] - 0s - loss: 5.6945e-06 - acc: 1.0000 - val_loss: 5.6665e-06 - val_acc: 1.0000
Epoch 3786/10000
100/100 [==============================] - 0s - loss: 5.6587e-06 - acc: 1.0000 - val_loss: 5.6277e-06 - val_acc: 1.0000
Epoch 3787/10000
100/100 [==============================] - 0s - loss: 5.6225e-06 - acc: 1.0000 - val_loss: 5.6295e-06 - val_acc: 1.0000
Epoch 3788/10000
100/100 [==============================] - 0s - loss: 5.6315e-06 - acc: 1.0000 - val_loss: 5.6098e-06 - val_acc: 1.0000
Epoch 3789/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 4.4337e-06 - acc: 1.0000 - val_loss: 4.4105e-06 - val_acc: 1.0000
Epoch 3901/10000
100/100 [==============================] - 0s - loss: 4.3952e-06 - acc: 1.0000 - val_loss: 4.3719e-06 - val_acc: 1.0000
Epoch 3902/10000
100/100 [==============================] - 0s - loss: 4.3740e-06 - acc: 1.0000 - val_loss: 4.3877e-06 - val_acc: 1.0000
Epoch 3903/10000
100/100 [==============================] - 0s - loss: 4.4136e-06 - acc: 1.0000 - val_loss: 4.3545e-06 - val_acc: 1.0000
Epoch 3904/10000
100/100 [==============================] - 0s - loss: 4.3593e-06 - acc: 1.0000 - val_loss: 4.3441e-06 - val_acc: 1.0000
Epoch 3905/10000
100/100 [==============================] - 0s - loss: 4.3452e-06 - acc: 1.0000 - val_loss: 4.3350e-06 - val_acc: 1.0000
Epoch 3906/10000
100/100 [==============================] - 0s - loss: 4.3656e-06 - acc: 1.0000 - val_loss: 4.3270e-06 - val_acc: 1.0000
Epoch 3907/10000
100/100 [==============================] 

100/100 [==============================] - ETA: 0s - loss: 2.8003e-06 - acc: 1.000 - 0s - loss: 3.4612e-06 - acc: 1.0000 - val_loss: 3.4189e-06 - val_acc: 1.0000
Epoch 4019/10000
100/100 [==============================] - 0s - loss: 3.4187e-06 - acc: 1.0000 - val_loss: 3.4127e-06 - val_acc: 1.0000
Epoch 4020/10000
100/100 [==============================] - 0s - loss: 3.4198e-06 - acc: 1.0000 - val_loss: 3.4016e-06 - val_acc: 1.0000
Epoch 4021/10000
100/100 [==============================] - 0s - loss: 3.4130e-06 - acc: 1.0000 - val_loss: 3.3962e-06 - val_acc: 1.0000
Epoch 4022/10000
100/100 [==============================] - 0s - loss: 3.4170e-06 - acc: 1.0000 - val_loss: 3.3913e-06 - val_acc: 1.0000
Epoch 4023/10000
100/100 [==============================] - 0s - loss: 3.3972e-06 - acc: 1.0000 - val_loss: 3.3825e-06 - val_acc: 1.0000
Epoch 4024/10000
100/100 [==============================] - 0s - loss: 3.3846e-06 - acc: 1.0000 - val_loss: 3.3774e-06 - val_acc: 1.0000
Epoch 4025/10000

100/100 [==============================] - 0s - loss: 2.6896e-06 - acc: 1.0000 - val_loss: 2.6836e-06 - val_acc: 1.0000
Epoch 4137/10000
100/100 [==============================] - 0s - loss: 2.6847e-06 - acc: 1.0000 - val_loss: 2.6798e-06 - val_acc: 1.0000
Epoch 4138/10000
100/100 [==============================] - 0s - loss: 2.6810e-06 - acc: 1.0000 - val_loss: 2.6725e-06 - val_acc: 1.0000
Epoch 4139/10000
100/100 [==============================] - 0s - loss: 2.6767e-06 - acc: 1.0000 - val_loss: 2.6723e-06 - val_acc: 1.0000
Epoch 4140/10000
100/100 [==============================] - 0s - loss: 2.6748e-06 - acc: 1.0000 - val_loss: 2.6647e-06 - val_acc: 1.0000
Epoch 4141/10000
100/100 [==============================] - 0s - loss: 2.6599e-06 - acc: 1.0000 - val_loss: 2.6580e-06 - val_acc: 1.0000
Epoch 4142/10000
100/100 [==============================] - 0s - loss: 2.6570e-06 - acc: 1.0000 - val_loss: 2.6553e-06 - val_acc: 1.0000
Epoch 4143/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 2.1708e-06 - acc: 1.0000 - val_loss: 2.1737e-06 - val_acc: 1.0000
Epoch 4255/10000
100/100 [==============================] - 0s - loss: 2.1599e-06 - acc: 1.0000 - val_loss: 2.1291e-06 - val_acc: 1.0000
Epoch 4256/10000
100/100 [==============================] - 0s - loss: 2.1629e-06 - acc: 1.0000 - val_loss: 2.1676e-06 - val_acc: 1.0000
Epoch 4257/10000
100/100 [==============================] - 0s - loss: 2.1558e-06 - acc: 1.0000 - val_loss: 2.1183e-06 - val_acc: 1.0000
Epoch 4258/10000
100/100 [==============================] - 0s - loss: 2.1348e-06 - acc: 1.0000 - val_loss: 2.1422e-06 - val_acc: 1.0000
Epoch 4259/10000
100/100 [==============================] - 0s - loss: 2.1561e-06 - acc: 1.0000 - val_loss: 2.1183e-06 - val_acc: 1.0000
Epoch 4260/10000
100/100 [==============================] - 0s - loss: 2.1134e-06 - acc: 1.0000 - val_loss: 2.1270e-06 - val_acc: 1.0000
Epoch 4261/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 1.7204e-06 - acc: 1.0000 - val_loss: 1.7223e-06 - val_acc: 1.0000
Epoch 4373/10000
100/100 [==============================] - 0s - loss: 1.7214e-06 - acc: 1.0000 - val_loss: 1.7151e-06 - val_acc: 1.0000
Epoch 4374/10000
100/100 [==============================] - 0s - loss: 1.7330e-06 - acc: 1.0000 - val_loss: 1.7149e-06 - val_acc: 1.0000
Epoch 4375/10000
100/100 [==============================] - 0s - loss: 1.7123e-06 - acc: 1.0000 - val_loss: 1.7081e-06 - val_acc: 1.0000
Epoch 4376/10000
100/100 [==============================] - 0s - loss: 1.7292e-06 - acc: 1.0000 - val_loss: 1.7156e-06 - val_acc: 1.0000
Epoch 4377/10000
100/100 [==============================] - 0s - loss: 1.7134e-06 - acc: 1.0000 - val_loss: 1.7037e-06 - val_acc: 1.0000
Epoch 4378/10000
100/100 [==============================] - 0s - loss: 1.7127e-06 - acc: 1.0000 - val_loss: 1.7068e-06 - val_acc: 1.0000
Epoch 4379/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 1.4482e-06 - acc: 1.0000 - val_loss: 1.4092e-06 - val_acc: 1.0000
Epoch 4491/10000
100/100 [==============================] - 0s - loss: 1.4092e-06 - acc: 1.0000 - val_loss: 1.4184e-06 - val_acc: 1.0000
Epoch 4492/10000
100/100 [==============================] - 0s - loss: 1.4229e-06 - acc: 1.0000 - val_loss: 1.4085e-06 - val_acc: 1.0000
Epoch 4493/10000
100/100 [==============================] - 0s - loss: 1.4018e-06 - acc: 1.0000 - val_loss: 1.4127e-06 - val_acc: 1.0000
Epoch 4494/10000
100/100 [==============================] - 0s - loss: 1.4201e-06 - acc: 1.0000 - val_loss: 1.4066e-06 - val_acc: 1.0000
Epoch 4495/10000
100/100 [==============================] - 0s - loss: 1.4124e-06 - acc: 1.0000 - val_loss: 1.4076e-06 - val_acc: 1.0000
Epoch 4496/10000
100/100 [==============================] - 0s - loss: 1.4087e-06 - acc: 1.0000 - val_loss: 1.3995e-06 - val_acc: 1.0000
Epoch 4497/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 1.2031e-06 - acc: 1.0000 - val_loss: 1.1867e-06 - val_acc: 1.0000
Epoch 4609/10000
100/100 [==============================] - 0s - loss: 1.1856e-06 - acc: 1.0000 - val_loss: 1.1903e-06 - val_acc: 1.0000
Epoch 4610/10000
100/100 [==============================] - 0s - loss: 1.1966e-06 - acc: 1.0000 - val_loss: 1.1869e-06 - val_acc: 1.0000
Epoch 4611/10000
100/100 [==============================] - 0s - loss: 1.1837e-06 - acc: 1.0000 - val_loss: 1.1843e-06 - val_acc: 1.0000
Epoch 4612/10000
100/100 [==============================] - 0s - loss: 1.2295e-06 - acc: 1.0000 - val_loss: 1.1943e-06 - val_acc: 1.0000
Epoch 4613/10000
100/100 [==============================] - 0s - loss: 1.1794e-06 - acc: 1.0000 - val_loss: 1.1940e-06 - val_acc: 1.0000
Epoch 4614/10000
100/100 [==============================] - 0s - loss: 1.1941e-06 - acc: 1.0000 - val_loss: 1.1937e-06 - val_acc: 1.0000
Epoch 4615/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 1.0231e-06 - acc: 1.0000 - val_loss: 1.0136e-06 - val_acc: 1.0000
Epoch 4727/10000
100/100 [==============================] - 0s - loss: 1.0302e-06 - acc: 1.0000 - val_loss: 1.0301e-06 - val_acc: 1.0000
Epoch 4728/10000
100/100 [==============================] - 0s - loss: 1.0521e-06 - acc: 1.0000 - val_loss: 1.0153e-06 - val_acc: 1.0000
Epoch 4729/10000
100/100 [==============================] - 0s - loss: 1.0195e-06 - acc: 1.0000 - val_loss: 1.0091e-06 - val_acc: 1.0000
Epoch 4730/10000
100/100 [==============================] - 0s - loss: 1.0096e-06 - acc: 1.0000 - val_loss: 1.0074e-06 - val_acc: 1.0000
Epoch 4731/10000
100/100 [==============================] - 0s - loss: 1.0159e-06 - acc: 1.0000 - val_loss: 1.0079e-06 - val_acc: 1.0000
Epoch 4732/10000
100/100 [==============================] - 0s - loss: 1.0140e-06 - acc: 1.0000 - val_loss: 1.0066e-06 - val_acc: 1.0000
Epoch 4733/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 9.4533e-07 - acc: 1.0000 - val_loss: 8.8818e-07 - val_acc: 1.0000
Epoch 4845/10000
100/100 [==============================] - 0s - loss: 8.8135e-07 - acc: 1.0000 - val_loss: 8.7380e-07 - val_acc: 1.0000
Epoch 4846/10000
100/100 [==============================] - 0s - loss: 8.7864e-07 - acc: 1.0000 - val_loss: 8.9719e-07 - val_acc: 1.0000
Epoch 4847/10000
100/100 [==============================] - 0s - loss: 8.8888e-07 - acc: 1.0000 - val_loss: 8.6916e-07 - val_acc: 1.0000
Epoch 4848/10000
100/100 [==============================] - 0s - loss: 8.6808e-07 - acc: 1.0000 - val_loss: 8.8975e-07 - val_acc: 1.0000
Epoch 4849/10000
100/100 [==============================] - 0s - loss: 8.8524e-07 - acc: 1.0000 - val_loss: 8.6742e-07 - val_acc: 1.0000
Epoch 4850/10000
100/100 [==============================] - 0s - loss: 8.9342e-07 - acc: 1.0000 - val_loss: 8.8493e-07 - val_acc: 1.0000
Epoch 4851/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 7.5897e-07 - acc: 1.0000 - val_loss: 7.5698e-07 - val_acc: 1.0000
Epoch 4963/10000
100/100 [==============================] - 0s - loss: 7.6089e-07 - acc: 1.0000 - val_loss: 7.5510e-07 - val_acc: 1.0000
Epoch 4964/10000
100/100 [==============================] - 0s - loss: 7.5739e-07 - acc: 1.0000 - val_loss: 7.5291e-07 - val_acc: 1.0000
Epoch 4965/10000
100/100 [==============================] - 0s - loss: 7.6498e-07 - acc: 1.0000 - val_loss: 7.5676e-07 - val_acc: 1.0000
Epoch 4966/10000
100/100 [==============================] - 0s - loss: 7.5481e-07 - acc: 1.0000 - val_loss: 7.5446e-07 - val_acc: 1.0000
Epoch 4967/10000
100/100 [==============================] - 0s - loss: 7.5420e-07 - acc: 1.0000 - val_loss: 7.5380e-07 - val_acc: 1.0000
Epoch 4968/10000
100/100 [==============================] - 0s - loss: 7.5328e-07 - acc: 1.0000 - val_loss: 7.4920e-07 - val_acc: 1.0000
Epoch 4969/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 7.0966e-07 - acc: 1.0000 - val_loss: 7.0246e-07 - val_acc: 1.0000
Epoch 5022/10000
100/100 [==============================] - 0s - loss: 7.0360e-07 - acc: 1.0000 - val_loss: 7.0171e-07 - val_acc: 1.0000
Epoch 5023/10000
100/100 [==============================] - 0s - loss: 7.0395e-07 - acc: 1.0000 - val_loss: 7.0167e-07 - val_acc: 1.0000
Epoch 5024/10000
100/100 [==============================] - 0s - loss: 7.0145e-07 - acc: 1.0000 - val_loss: 6.9995e-07 - val_acc: 1.0000
Epoch 5025/10000
100/100 [==============================] - 0s - loss: 6.9973e-07 - acc: 1.0000 - val_loss: 6.9934e-07 - val_acc: 1.0000
Epoch 5026/10000
100/100 [==============================] - 0s - loss: 7.0062e-07 - acc: 1.0000 - val_loss: 6.9821e-07 - val_acc: 1.0000
Epoch 5027/10000
100/100 [==============================] - 0s - loss: 6.9846e-07 - acc: 1.0000 - val_loss: 6.9788e-07 - val_acc: 1.0000
Epoch 5028/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 6.7429e-07 - acc: 1.0000 - val_loss: 6.5825e-07 - val_acc: 1.0000
Epoch 5080/10000
100/100 [==============================] - 0s - loss: 6.7995e-07 - acc: 1.0000 - val_loss: 6.6835e-07 - val_acc: 1.0000
Epoch 5081/10000
100/100 [==============================] - 0s - loss: 6.6395e-07 - acc: 1.0000 - val_loss: 6.5390e-07 - val_acc: 1.0000
Epoch 5082/10000
100/100 [==============================] - 0s - loss: 6.7344e-07 - acc: 1.0000 - val_loss: 6.6355e-07 - val_acc: 1.0000
Epoch 5083/10000
100/100 [==============================] - 0s - loss: 6.5730e-07 - acc: 1.0000 - val_loss: 6.5590e-07 - val_acc: 1.0000
Epoch 5084/10000
100/100 [==============================] - 0s - loss: 6.5979e-07 - acc: 1.0000 - val_loss: 6.5340e-07 - val_acc: 1.0000
Epoch 5085/10000
100/100 [==============================] - 0s - loss: 6.5289e-07 - acc: 1.0000 - val_loss: 6.5043e-07 - val_acc: 1.0000
Epoch 5086/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 5.6756e-07 - acc: 1.0000 - val_loss: 5.6757e-07 - val_acc: 1.0000
Epoch 5197/10000
100/100 [==============================] - 0s - loss: 5.7482e-07 - acc: 1.0000 - val_loss: 5.6720e-07 - val_acc: 1.0000
Epoch 5198/10000
100/100 [==============================] - 0s - loss: 5.6800e-07 - acc: 1.0000 - val_loss: 5.6783e-07 - val_acc: 1.0000
Epoch 5199/10000
100/100 [==============================] - 0s - loss: 5.8463e-07 - acc: 1.0000 - val_loss: 5.7296e-07 - val_acc: 1.0000
Epoch 5200/10000
100/100 [==============================] - 0s - loss: 5.6545e-07 - acc: 1.0000 - val_loss: 5.7251e-07 - val_acc: 1.0000
Epoch 5201/10000
100/100 [==============================] - 0s - loss: 5.7377e-07 - acc: 1.0000 - val_loss: 5.6763e-07 - val_acc: 1.0000
Epoch 5202/10000
100/100 [==============================] - 0s - loss: 5.7089e-07 - acc: 1.0000 - val_loss: 5.6936e-07 - val_acc: 1.0000
Epoch 5203/10000
100/100 [==============================] 

100/100 [==============================] - ETA: 0s - loss: 5.5293e-07 - acc: 1.000 - 0s - loss: 4.9244e-07 - acc: 1.0000 - val_loss: 4.9038e-07 - val_acc: 1.0000
Epoch 5315/10000
100/100 [==============================] - 0s - loss: 5.0798e-07 - acc: 1.0000 - val_loss: 4.9235e-07 - val_acc: 1.0000
Epoch 5316/10000
100/100 [==============================] - 0s - loss: 5.3319e-07 - acc: 1.0000 - val_loss: 4.9469e-07 - val_acc: 1.0000
Epoch 5317/10000
100/100 [==============================] - 0s - loss: 4.9083e-07 - acc: 1.0000 - val_loss: 4.9345e-07 - val_acc: 1.0000
Epoch 5318/10000
100/100 [==============================] - 0s - loss: 4.9923e-07 - acc: 1.0000 - val_loss: 4.8807e-07 - val_acc: 1.0000
Epoch 5319/10000
100/100 [==============================] - 0s - loss: 4.8569e-07 - acc: 1.0000 - val_loss: 4.9617e-07 - val_acc: 1.0000
Epoch 5320/10000
100/100 [==============================] - 0s - loss: 4.9617e-07 - acc: 1.0000 - val_loss: 4.8621e-07 - val_acc: 1.0000
Epoch 5321/10000

100/100 [==============================] - 0s - loss: 3.9238e-07 - acc: 1.0000 - val_loss: 3.9623e-07 - val_acc: 1.0000
Epoch 5504/10000
100/100 [==============================] - 0s - loss: 3.9458e-07 - acc: 1.0000 - val_loss: 3.8307e-07 - val_acc: 1.0000
Epoch 5505/10000
100/100 [==============================] - 0s - loss: 3.9029e-07 - acc: 1.0000 - val_loss: 3.9455e-07 - val_acc: 1.0000
Epoch 5506/10000
100/100 [==============================] - 0s - loss: 3.8911e-07 - acc: 1.0000 - val_loss: 3.8481e-07 - val_acc: 1.0000
Epoch 5507/10000
100/100 [==============================] - 0s - loss: 3.8470e-07 - acc: 1.0000 - val_loss: 3.8557e-07 - val_acc: 1.0000
Epoch 5508/10000
100/100 [==============================] - 0s - loss: 3.8347e-07 - acc: 1.0000 - val_loss: 3.8212e-07 - val_acc: 1.0000
Epoch 5509/10000
100/100 [==============================] - 0s - loss: 3.8446e-07 - acc: 1.0000 - val_loss: 3.8273e-07 - val_acc: 1.0000
Epoch 5510/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 3.4364e-07 - acc: 1.0000 - val_loss: 3.3076e-07 - val_acc: 1.0000
Epoch 5620/10000
100/100 [==============================] - 0s - loss: 3.2798e-07 - acc: 1.0000 - val_loss: 3.4200e-07 - val_acc: 1.0000
Epoch 5621/10000
100/100 [==============================] - 0s - loss: 3.4512e-07 - acc: 1.0000 - val_loss: 3.3006e-07 - val_acc: 1.0000
Epoch 5622/10000
100/100 [==============================] - 0s - loss: 3.3206e-07 - acc: 1.0000 - val_loss: 3.4511e-07 - val_acc: 1.0000
Epoch 5623/10000
100/100 [==============================] - 0s - loss: 3.4292e-07 - acc: 1.0000 - val_loss: 3.2982e-07 - val_acc: 1.0000
Epoch 5624/10000
100/100 [==============================] - 0s - loss: 3.3561e-07 - acc: 1.0000 - val_loss: 3.4360e-07 - val_acc: 1.0000
Epoch 5625/10000
100/100 [==============================] - 0s - loss: 3.3894e-07 - acc: 1.0000 - val_loss: 3.3280e-07 - val_acc: 1.0000
Epoch 5626/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 2.8627e-07 - acc: 1.0000 - val_loss: 2.8893e-07 - val_acc: 1.0000
Epoch 5737/10000
100/100 [==============================] - 0s - loss: 2.9888e-07 - acc: 1.0000 - val_loss: 2.8588e-07 - val_acc: 1.0000
Epoch 5738/10000
100/100 [==============================] - 0s - loss: 3.0238e-07 - acc: 1.0000 - val_loss: 2.9756e-07 - val_acc: 1.0000
Epoch 5739/10000
100/100 [==============================] - 0s - loss: 2.9166e-07 - acc: 1.0000 - val_loss: 2.8945e-07 - val_acc: 1.0000
Epoch 5740/10000
100/100 [==============================] - 0s - loss: 2.9750e-07 - acc: 1.0000 - val_loss: 2.9212e-07 - val_acc: 1.0000
Epoch 5741/10000
100/100 [==============================] - 0s - loss: 2.8476e-07 - acc: 1.0000 - val_loss: 2.9691e-07 - val_acc: 1.0000
Epoch 5742/10000
100/100 [==============================] - 0s - loss: 3.0755e-07 - acc: 1.0000 - val_loss: 2.8523e-07 - val_acc: 1.0000
Epoch 5743/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 2.4692e-07 - acc: 1.0000 - val_loss: 2.5079e-07 - val_acc: 1.0000
Epoch 5855/10000
100/100 [==============================] - 0s - loss: 2.6062e-07 - acc: 1.0000 - val_loss: 2.4777e-07 - val_acc: 1.0000
Epoch 5856/10000
100/100 [==============================] - 0s - loss: 2.9032e-07 - acc: 1.0000 - val_loss: 2.5684e-07 - val_acc: 1.0000
Epoch 5857/10000
100/100 [==============================] - 0s - loss: 2.6650e-07 - acc: 1.0000 - val_loss: 2.6874e-07 - val_acc: 1.0000
Epoch 5858/10000
100/100 [==============================] - 0s - loss: 2.6087e-07 - acc: 1.0000 - val_loss: 2.4780e-07 - val_acc: 1.0000
Epoch 5859/10000
100/100 [==============================] - 0s - loss: 2.5903e-07 - acc: 1.0000 - val_loss: 2.5470e-07 - val_acc: 1.0000
Epoch 5860/10000
100/100 [==============================] - 0s - loss: 2.6546e-07 - acc: 1.0000 - val_loss: 2.6017e-07 - val_acc: 1.0000
Epoch 5861/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 2.5180e-07 - acc: 1.0000 - val_loss: 2.2430e-07 - val_acc: 1.0000
Epoch 5973/10000
100/100 [==============================] - 0s - loss: 2.2171e-07 - acc: 1.0000 - val_loss: 2.5013e-07 - val_acc: 1.0000
Epoch 5974/10000
100/100 [==============================] - 0s - loss: 2.5036e-07 - acc: 1.0000 - val_loss: 2.1757e-07 - val_acc: 1.0000
Epoch 5975/10000
100/100 [==============================] - 0s - loss: 2.2925e-07 - acc: 1.0000 - val_loss: 2.4633e-07 - val_acc: 1.0000
Epoch 5976/10000
100/100 [==============================] - 0s - loss: 2.3252e-07 - acc: 1.0000 - val_loss: 2.3627e-07 - val_acc: 1.0000
Epoch 5977/10000
100/100 [==============================] - 0s - loss: 2.3276e-07 - acc: 1.0000 - val_loss: 2.1163e-07 - val_acc: 1.0000
Epoch 5978/10000
100/100 [==============================] - 0s - loss: 2.1552e-07 - acc: 1.0000 - val_loss: 2.2319e-07 - val_acc: 1.0000
Epoch 5979/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 1.8998e-07 - acc: 1.0000 - val_loss: 1.8497e-07 - val_acc: 1.0000
Epoch 6091/10000
100/100 [==============================] - 0s - loss: 1.9345e-07 - acc: 1.0000 - val_loss: 1.8529e-07 - val_acc: 1.0000
Epoch 6092/10000
100/100 [==============================] - ETA: 0s - loss: 2.6079e-07 - acc: 1.000 - 0s - loss: 1.8971e-07 - acc: 1.0000 - val_loss: 1.8842e-07 - val_acc: 1.0000
Epoch 6093/10000
100/100 [==============================] - 0s - loss: 1.9439e-07 - acc: 1.0000 - val_loss: 1.8597e-07 - val_acc: 1.0000
Epoch 6094/10000
100/100 [==============================] - 0s - loss: 1.8521e-07 - acc: 1.0000 - val_loss: 1.8507e-07 - val_acc: 1.0000
Epoch 6095/10000
100/100 [==============================] - 0s - loss: 1.8710e-07 - acc: 1.0000 - val_loss: 1.8503e-07 - val_acc: 1.0000
Epoch 6096/10000
100/100 [==============================] - 0s - loss: 1.8718e-07 - acc: 1.0000 - val_loss: 1.8392e-07 - val_acc: 1.0000
Epoch 6097/10000

100/100 [==============================] - 0s - loss: 1.6821e-07 - acc: 1.0000 - val_loss: 1.6061e-07 - val_acc: 1.0000
Epoch 6209/10000
100/100 [==============================] - 0s - loss: 1.6909e-07 - acc: 1.0000 - val_loss: 1.6662e-07 - val_acc: 1.0000
Epoch 6210/10000
100/100 [==============================] - 0s - loss: 1.6183e-07 - acc: 1.0000 - val_loss: 1.6597e-07 - val_acc: 1.0000
Epoch 6211/10000
100/100 [==============================] - 0s - loss: 1.6611e-07 - acc: 1.0000 - val_loss: 1.5982e-07 - val_acc: 1.0000
Epoch 6212/10000
100/100 [==============================] - 0s - loss: 1.6366e-07 - acc: 1.0000 - val_loss: 1.6325e-07 - val_acc: 1.0000
Epoch 6213/10000
100/100 [==============================] - 0s - loss: 1.6383e-07 - acc: 1.0000 - val_loss: 1.6252e-07 - val_acc: 1.0000
Epoch 6214/10000
100/100 [==============================] - ETA: 0s - loss: 1.8433e-07 - acc: 1.000 - 0s - loss: 1.6130e-07 - acc: 1.0000 - val_loss: 1.5915e-07 - val_acc: 1.0000
Epoch 6215/10000

100/100 [==============================] - ETA: 0s - loss: 1.9255e-07 - acc: 1.000 - 0s - loss: 1.5563e-07 - acc: 1.0000 - val_loss: 1.5360e-07 - val_acc: 1.0000
Epoch 6267/10000
100/100 [==============================] - 0s - loss: 1.5540e-07 - acc: 1.0000 - val_loss: 1.5031e-07 - val_acc: 1.0000
Epoch 6268/10000
100/100 [==============================] - 0s - loss: 1.5163e-07 - acc: 1.0000 - val_loss: 1.4951e-07 - val_acc: 1.0000
Epoch 6269/10000
100/100 [==============================] - 0s - loss: 1.4953e-07 - acc: 1.0000 - val_loss: 1.5057e-07 - val_acc: 1.0000
Epoch 6270/10000
100/100 [==============================] - 0s - loss: 1.5008e-07 - acc: 1.0000 - val_loss: 1.4917e-07 - val_acc: 1.0000
Epoch 6271/10000
100/100 [==============================] - 0s - loss: 1.4968e-07 - acc: 1.0000 - val_loss: 1.4885e-07 - val_acc: 1.0000
Epoch 6272/10000
100/100 [==============================] - 0s - loss: 1.4906e-07 - acc: 1.0000 - val_loss: 1.4915e-07 - val_acc: 1.0000
Epoch 6273/10000

100/100 [==============================] - 0s - loss: 1.3368e-07 - acc: 1.0000 - val_loss: 1.3749e-07 - val_acc: 1.0000
Epoch 6385/10000
100/100 [==============================] - 0s - loss: 1.3813e-07 - acc: 1.0000 - val_loss: 1.3063e-07 - val_acc: 1.0000
Epoch 6386/10000
100/100 [==============================] - 0s - loss: 1.3055e-07 - acc: 1.0000 - val_loss: 1.3606e-07 - val_acc: 1.0000
Epoch 6387/10000
100/100 [==============================] - 0s - loss: 1.3413e-07 - acc: 1.0000 - val_loss: 1.3344e-07 - val_acc: 1.0000
Epoch 6388/10000
100/100 [==============================] - 0s - loss: 1.4016e-07 - acc: 1.0000 - val_loss: 1.3065e-07 - val_acc: 1.0000
Epoch 6389/10000
100/100 [==============================] - 0s - loss: 1.4093e-07 - acc: 1.0000 - val_loss: 1.3815e-07 - val_acc: 1.0000
Epoch 6390/10000
100/100 [==============================] - 0s - loss: 1.3488e-07 - acc: 1.0000 - val_loss: 1.3958e-07 - val_acc: 1.0000
Epoch 6391/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 1.2215e-07 - acc: 1.0000 - val_loss: 1.1584e-07 - val_acc: 1.0000
Epoch 6503/10000
100/100 [==============================] - 0s - loss: 1.1451e-07 - acc: 1.0000 - val_loss: 1.1953e-07 - val_acc: 1.0000
Epoch 6504/10000
100/100 [==============================] - 0s - loss: 1.2061e-07 - acc: 1.0000 - val_loss: 1.1559e-07 - val_acc: 1.0000
Epoch 6505/10000
100/100 [==============================] - 0s - loss: 1.1837e-07 - acc: 1.0000 - val_loss: 1.1694e-07 - val_acc: 1.0000
Epoch 6506/10000
100/100 [==============================] - 0s - loss: 1.2983e-07 - acc: 1.0000 - val_loss: 1.1720e-07 - val_acc: 1.0000
Epoch 6507/10000
100/100 [==============================] - 0s - loss: 1.1373e-07 - acc: 1.0000 - val_loss: 1.2247e-07 - val_acc: 1.0000
Epoch 6508/10000
100/100 [==============================] - 0s - loss: 1.2068e-07 - acc: 1.0000 - val_loss: 1.1448e-07 - val_acc: 1.0000
Epoch 6509/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 1.0697e-07 - acc: 1.0000 - val_loss: 1.1260e-07 - val_acc: 1.0000
Epoch 6621/10000
100/100 [==============================] - 0s - loss: 1.1196e-07 - acc: 1.0000 - val_loss: 1.0901e-07 - val_acc: 1.0000
Epoch 6622/10000
100/100 [==============================] - 0s - loss: 1.0749e-07 - acc: 1.0000 - val_loss: 1.0418e-07 - val_acc: 1.0000
Epoch 6623/10000
100/100 [==============================] - 0s - loss: 1.0604e-07 - acc: 1.0000 - val_loss: 1.0116e-07 - val_acc: 1.0000
Epoch 6624/10000
100/100 [==============================] - ETA: 0s - loss: 8.4447e-08 - acc: 1.000 - 0s - loss: 1.0750e-07 - acc: 1.0000 - val_loss: 1.0354e-07 - val_acc: 1.0000
Epoch 6625/10000
100/100 [==============================] - 0s - loss: 1.1164e-07 - acc: 1.0000 - val_loss: 1.0513e-07 - val_acc: 1.0000
Epoch 6626/10000
100/100 [==============================] - 0s - loss: 1.0351e-07 - acc: 1.0000 - val_loss: 1.0718e-07 - val_acc: 1.0000
Epoch 6627/10000

100/100 [==============================] - 0s - loss: 9.0683e-08 - acc: 1.0000 - val_loss: 8.9974e-08 - val_acc: 1.0000
Epoch 6739/10000
100/100 [==============================] - 0s - loss: 9.1327e-08 - acc: 1.0000 - val_loss: 8.8976e-08 - val_acc: 1.0000
Epoch 6740/10000
100/100 [==============================] - 0s - loss: 9.3351e-08 - acc: 1.0000 - val_loss: 8.9335e-08 - val_acc: 1.0000
Epoch 6741/10000
100/100 [==============================] - 0s - loss: 8.9419e-08 - acc: 1.0000 - val_loss: 9.2455e-08 - val_acc: 1.0000
Epoch 6742/10000
100/100 [==============================] - 0s - loss: 9.0419e-08 - acc: 1.0000 - val_loss: 9.1723e-08 - val_acc: 1.0000
Epoch 6743/10000
100/100 [==============================] - 0s - loss: 9.1408e-08 - acc: 1.0000 - val_loss: 8.8823e-08 - val_acc: 1.0000
Epoch 6744/10000
100/100 [==============================] - 0s - loss: 9.6014e-08 - acc: 1.0000 - val_loss: 8.8549e-08 - val_acc: 1.0000
Epoch 6745/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 8.0641e-08 - acc: 1.0000 - val_loss: 8.1304e-08 - val_acc: 1.0000
Epoch 6857/10000
100/100 [==============================] - 0s - loss: 8.4390e-08 - acc: 1.0000 - val_loss: 7.9120e-08 - val_acc: 1.0000
Epoch 6858/10000
100/100 [==============================] - 0s - loss: 8.0361e-08 - acc: 1.0000 - val_loss: 8.0412e-08 - val_acc: 1.0000
Epoch 6859/10000
100/100 [==============================] - 0s - loss: 7.9028e-08 - acc: 1.0000 - val_loss: 8.2806e-08 - val_acc: 1.0000
Epoch 6860/10000
100/100 [==============================] - 0s - loss: 8.2335e-08 - acc: 1.0000 - val_loss: 8.0548e-08 - val_acc: 1.0000
Epoch 6861/10000
100/100 [==============================] - 0s - loss: 8.8990e-08 - acc: 1.0000 - val_loss: 7.8505e-08 - val_acc: 1.0000
Epoch 6862/10000
100/100 [==============================] - 0s - loss: 8.2758e-08 - acc: 1.0000 - val_loss: 8.2521e-08 - val_acc: 1.0000
Epoch 6863/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 8.1679e-08 - acc: 1.0000 - val_loss: 7.9661e-08 - val_acc: 1.0000
Epoch 6975/10000
100/100 [==============================] - 0s - loss: 7.7460e-08 - acc: 1.0000 - val_loss: 8.1501e-08 - val_acc: 1.0000
Epoch 6976/10000
100/100 [==============================] - 0s - loss: 7.6505e-08 - acc: 1.0000 - val_loss: 7.7935e-08 - val_acc: 1.0000
Epoch 6977/10000
100/100 [==============================] - 0s - loss: 7.6204e-08 - acc: 1.0000 - val_loss: 7.1291e-08 - val_acc: 1.0000
Epoch 6978/10000
100/100 [==============================] - 0s - loss: 7.2227e-08 - acc: 1.0000 - val_loss: 7.1943e-08 - val_acc: 1.0000
Epoch 6979/10000
100/100 [==============================] - 0s - loss: 7.2309e-08 - acc: 1.0000 - val_loss: 7.1575e-08 - val_acc: 1.0000
Epoch 6980/10000
100/100 [==============================] - 0s - loss: 7.2383e-08 - acc: 1.0000 - val_loss: 7.0754e-08 - val_acc: 1.0000
Epoch 6981/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 7.0583e-08 - acc: 1.0000 - val_loss: 7.7743e-08 - val_acc: 1.0000
Epoch 7093/10000
100/100 [==============================] - 0s - loss: 7.3815e-08 - acc: 1.0000 - val_loss: 6.7385e-08 - val_acc: 1.0000
Epoch 7094/10000
100/100 [==============================] - 0s - loss: 8.1892e-08 - acc: 1.0000 - val_loss: 6.9596e-08 - val_acc: 1.0000
Epoch 7095/10000
100/100 [==============================] - 0s - loss: 9.2213e-08 - acc: 1.0000 - val_loss: 6.4015e-08 - val_acc: 1.0000
Epoch 7096/10000
100/100 [==============================] - 0s - loss: 8.3914e-08 - acc: 1.0000 - val_loss: 6.9501e-08 - val_acc: 1.0000
Epoch 7097/10000
100/100 [==============================] - 0s - loss: 7.9366e-08 - acc: 1.0000 - val_loss: 7.9509e-08 - val_acc: 1.0000
Epoch 7098/10000
100/100 [==============================] - 0s - loss: 7.7915e-08 - acc: 1.0000 - val_loss: 8.9224e-08 - val_acc: 1.0000
Epoch 7099/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 6.9805e-08 - acc: 1.0000 - val_loss: 6.3864e-08 - val_acc: 1.0000
Epoch 7211/10000
100/100 [==============================] - 0s - loss: 6.7802e-08 - acc: 1.0000 - val_loss: 6.4008e-08 - val_acc: 1.0000
Epoch 7212/10000
100/100 [==============================] - 0s - loss: 6.6169e-08 - acc: 1.0000 - val_loss: 6.3032e-08 - val_acc: 1.0000
Epoch 7213/10000
100/100 [==============================] - 0s - loss: 6.6436e-08 - acc: 1.0000 - val_loss: 6.1499e-08 - val_acc: 1.0000
Epoch 7214/10000
100/100 [==============================] - 0s - loss: 6.8767e-08 - acc: 1.0000 - val_loss: 5.9835e-08 - val_acc: 1.0000
Epoch 7215/10000
100/100 [==============================] - 0s - loss: 5.7948e-08 - acc: 1.0000 - val_loss: 6.3840e-08 - val_acc: 1.0000
Epoch 7216/10000
100/100 [==============================] - 0s - loss: 6.2283e-08 - acc: 1.0000 - val_loss: 6.3340e-08 - val_acc: 1.0000
Epoch 7217/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 6.4604e-08 - acc: 1.0000 - val_loss: 5.9094e-08 - val_acc: 1.0000
Epoch 7329/10000
100/100 [==============================] - 0s - loss: 5.7521e-08 - acc: 1.0000 - val_loss: 5.9719e-08 - val_acc: 1.0000
Epoch 7330/10000
100/100 [==============================] - 0s - loss: 5.7740e-08 - acc: 1.0000 - val_loss: 5.7601e-08 - val_acc: 1.0000
Epoch 7331/10000
100/100 [==============================] - 0s - loss: 6.5010e-08 - acc: 1.0000 - val_loss: 5.7406e-08 - val_acc: 1.0000
Epoch 7332/10000
100/100 [==============================] - 0s - loss: 6.1161e-08 - acc: 1.0000 - val_loss: 5.3426e-08 - val_acc: 1.0000
Epoch 7333/10000
100/100 [==============================] - 0s - loss: 5.1987e-08 - acc: 1.0000 - val_loss: 6.4788e-08 - val_acc: 1.0000
Epoch 7334/10000
100/100 [==============================] - 0s - loss: 6.0764e-08 - acc: 1.0000 - val_loss: 5.7464e-08 - val_acc: 1.0000
Epoch 7335/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 4.9609e-08 - acc: 1.0000 - val_loss: 5.2252e-08 - val_acc: 1.0000
Epoch 7446/10000
100/100 [==============================] - 0s - loss: 5.0986e-08 - acc: 1.0000 - val_loss: 5.2611e-08 - val_acc: 1.0000
Epoch 7447/10000
100/100 [==============================] - 0s - loss: 5.0953e-08 - acc: 1.0000 - val_loss: 5.2338e-08 - val_acc: 1.0000
Epoch 7448/10000
100/100 [==============================] - 0s - loss: 5.1739e-08 - acc: 1.0000 - val_loss: 4.9943e-08 - val_acc: 1.0000
Epoch 7449/10000
100/100 [==============================] - 0s - loss: 5.1243e-08 - acc: 1.0000 - val_loss: 4.9942e-08 - val_acc: 1.0000
Epoch 7450/10000
100/100 [==============================] - 0s - loss: 5.3035e-08 - acc: 1.0000 - val_loss: 5.0576e-08 - val_acc: 1.0000
Epoch 7451/10000
100/100 [==============================] - 0s - loss: 5.9290e-08 - acc: 1.0000 - val_loss: 5.0008e-08 - val_acc: 1.0000
Epoch 7452/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 4.8336e-08 - acc: 1.0000 - val_loss: 4.9346e-08 - val_acc: 1.0000
Epoch 7505/10000
100/100 [==============================] - 0s - loss: 4.9833e-08 - acc: 1.0000 - val_loss: 4.8752e-08 - val_acc: 1.0000
Epoch 7506/10000
100/100 [==============================] - 0s - loss: 4.8202e-08 - acc: 1.0000 - val_loss: 4.9188e-08 - val_acc: 1.0000
Epoch 7507/10000
100/100 [==============================] - 0s - loss: 5.0210e-08 - acc: 1.0000 - val_loss: 5.1379e-08 - val_acc: 1.0000
Epoch 7508/10000
100/100 [==============================] - 0s - loss: 5.0843e-08 - acc: 1.0000 - val_loss: 4.7760e-08 - val_acc: 1.0000
Epoch 7509/10000
100/100 [==============================] - 0s - loss: 4.8824e-08 - acc: 1.0000 - val_loss: 4.7729e-08 - val_acc: 1.0000
Epoch 7510/10000
100/100 [==============================] - 0s - loss: 4.8489e-08 - acc: 1.0000 - val_loss: 4.7950e-08 - val_acc: 1.0000
Epoch 7511/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 4.9668e-08 - acc: 1.0000 - val_loss: 4.4285e-08 - val_acc: 1.0000
Epoch 7623/10000
100/100 [==============================] - 0s - loss: 5.0951e-08 - acc: 1.0000 - val_loss: 4.4452e-08 - val_acc: 1.0000
Epoch 7624/10000
100/100 [==============================] - 0s - loss: 4.8340e-08 - acc: 1.0000 - val_loss: 4.5399e-08 - val_acc: 1.0000
Epoch 7625/10000
100/100 [==============================] - 0s - loss: 4.4550e-08 - acc: 1.0000 - val_loss: 4.9455e-08 - val_acc: 1.0000
Epoch 7626/10000
100/100 [==============================] - ETA: 0s - loss: 3.9542e-08 - acc: 1.000 - 0s - loss: 4.6301e-08 - acc: 1.0000 - val_loss: 5.4512e-08 - val_acc: 1.0000
Epoch 7627/10000
100/100 [==============================] - 0s - loss: 5.1518e-08 - acc: 1.0000 - val_loss: 4.9089e-08 - val_acc: 1.0000
Epoch 7628/10000
100/100 [==============================] - 0s - loss: 5.1876e-08 - acc: 1.0000 - val_loss: 4.6393e-08 - val_acc: 1.0000
Epoch 7629/10000

100/100 [==============================] - 0s - loss: 4.9922e-08 - acc: 1.0000 - val_loss: 4.3025e-08 - val_acc: 1.0000
Epoch 7741/10000
100/100 [==============================] - 0s - loss: 4.4515e-08 - acc: 1.0000 - val_loss: 4.2564e-08 - val_acc: 1.0000
Epoch 7742/10000
100/100 [==============================] - 0s - loss: 4.3112e-08 - acc: 1.0000 - val_loss: 4.4070e-08 - val_acc: 1.0000
Epoch 7743/10000
100/100 [==============================] - 0s - loss: 4.2148e-08 - acc: 1.0000 - val_loss: 4.6343e-08 - val_acc: 1.0000
Epoch 7744/10000
100/100 [==============================] - 0s - loss: 4.4697e-08 - acc: 1.0000 - val_loss: 4.3834e-08 - val_acc: 1.0000
Epoch 7745/10000
100/100 [==============================] - 0s - loss: 4.3740e-08 - acc: 1.0000 - val_loss: 4.5710e-08 - val_acc: 1.0000
Epoch 7746/10000
100/100 [==============================] - 0s - loss: 5.0359e-08 - acc: 1.0000 - val_loss: 4.6149e-08 - val_acc: 1.0000
Epoch 7747/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 4.0107e-08 - acc: 1.0000 - val_loss: 4.2851e-08 - val_acc: 1.0000
Epoch 7859/10000
100/100 [==============================] - 0s - loss: 4.1476e-08 - acc: 1.0000 - val_loss: 4.2635e-08 - val_acc: 1.0000
Epoch 7860/10000
100/100 [==============================] - 0s - loss: 4.3231e-08 - acc: 1.0000 - val_loss: 4.9347e-08 - val_acc: 1.0000
Epoch 7861/10000
100/100 [==============================] - 0s - loss: 4.7886e-08 - acc: 1.0000 - val_loss: 4.4102e-08 - val_acc: 1.0000
Epoch 7862/10000
100/100 [==============================] - 0s - loss: 4.3917e-08 - acc: 1.0000 - val_loss: 3.9823e-08 - val_acc: 1.0000
Epoch 7863/10000
100/100 [==============================] - 0s - loss: 4.5692e-08 - acc: 1.0000 - val_loss: 4.0513e-08 - val_acc: 1.0000
Epoch 7864/10000
100/100 [==============================] - 0s - loss: 4.4555e-08 - acc: 1.0000 - val_loss: 3.9400e-08 - val_acc: 1.0000
Epoch 7865/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 4.8478e-08 - acc: 1.0000 - val_loss: 3.8209e-08 - val_acc: 1.0000
Epoch 7977/10000
100/100 [==============================] - 0s - loss: 5.5865e-08 - acc: 1.0000 - val_loss: 3.8796e-08 - val_acc: 1.0000
Epoch 7978/10000
100/100 [==============================] - 0s - loss: 5.1557e-08 - acc: 1.0000 - val_loss: 3.7634e-08 - val_acc: 1.0000
Epoch 7979/10000
100/100 [==============================] - 0s - loss: 4.8802e-08 - acc: 1.0000 - val_loss: 3.8057e-08 - val_acc: 1.0000
Epoch 7980/10000
100/100 [==============================] - 0s - loss: 4.4412e-08 - acc: 1.0000 - val_loss: 3.9884e-08 - val_acc: 1.0000
Epoch 7981/10000
100/100 [==============================] - 0s - loss: 4.9824e-08 - acc: 1.0000 - val_loss: 3.9813e-08 - val_acc: 1.0000
Epoch 7982/10000
100/100 [==============================] - 0s - loss: 4.2692e-08 - acc: 1.0000 - val_loss: 4.2130e-08 - val_acc: 1.0000
Epoch 7983/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 3.9071e-08 - acc: 1.0000 - val_loss: 3.6678e-08 - val_acc: 1.0000
Epoch 8036/10000
100/100 [==============================] - 0s - loss: 3.6585e-08 - acc: 1.0000 - val_loss: 3.8960e-08 - val_acc: 1.0000
Epoch 8037/10000
100/100 [==============================] - 0s - loss: 3.7973e-08 - acc: 1.0000 - val_loss: 3.7852e-08 - val_acc: 1.0000
Epoch 8038/10000
100/100 [==============================] - 0s - loss: 3.7636e-08 - acc: 1.0000 - val_loss: 3.8265e-08 - val_acc: 1.0000
Epoch 8039/10000
100/100 [==============================] - 0s - loss: 3.9117e-08 - acc: 1.0000 - val_loss: 3.6771e-08 - val_acc: 1.0000
Epoch 8040/10000
100/100 [==============================] - 0s - loss: 3.8274e-08 - acc: 1.0000 - val_loss: 3.8997e-08 - val_acc: 1.0000
Epoch 8041/10000
100/100 [==============================] - 0s - loss: 3.8375e-08 - acc: 1.0000 - val_loss: 3.7163e-08 - val_acc: 1.0000
Epoch 8042/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 3.8215e-08 - acc: 1.0000 - val_loss: 3.6144e-08 - val_acc: 1.0000
Epoch 8154/10000
100/100 [==============================] - 0s - loss: 3.9246e-08 - acc: 1.0000 - val_loss: 3.6236e-08 - val_acc: 1.0000
Epoch 8155/10000
100/100 [==============================] - 0s - loss: 4.4800e-08 - acc: 1.0000 - val_loss: 4.1112e-08 - val_acc: 1.0000
Epoch 8156/10000
100/100 [==============================] - 0s - loss: 5.6489e-08 - acc: 1.0000 - val_loss: 4.6241e-08 - val_acc: 1.0000
Epoch 8157/10000
100/100 [==============================] - 0s - loss: 4.6438e-08 - acc: 1.0000 - val_loss: 3.5377e-08 - val_acc: 1.0000
Epoch 8158/10000
100/100 [==============================] - 0s - loss: 4.0614e-08 - acc: 1.0000 - val_loss: 3.5031e-08 - val_acc: 1.0000
Epoch 8159/10000
100/100 [==============================] - 0s - loss: 4.1692e-08 - acc: 1.0000 - val_loss: 3.5320e-08 - val_acc: 1.0000
Epoch 8160/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 3.3742e-08 - acc: 1.0000 - val_loss: 3.3700e-08 - val_acc: 1.0000
Epoch 8272/10000
100/100 [==============================] - 0s - loss: 3.4429e-08 - acc: 1.0000 - val_loss: 3.3746e-08 - val_acc: 1.0000
Epoch 8273/10000
100/100 [==============================] - 0s - loss: 3.4026e-08 - acc: 1.0000 - val_loss: 3.3689e-08 - val_acc: 1.0000
Epoch 8274/10000
100/100 [==============================] - 0s - loss: 3.3669e-08 - acc: 1.0000 - val_loss: 3.3510e-08 - val_acc: 1.0000
Epoch 8275/10000
100/100 [==============================] - ETA: 0s - loss: 3.6825e-08 - acc: 1.000 - 0s - loss: 3.7244e-08 - acc: 1.0000 - val_loss: 3.7211e-08 - val_acc: 1.0000
Epoch 8276/10000
100/100 [==============================] - 0s - loss: 3.6837e-08 - acc: 1.0000 - val_loss: 3.5280e-08 - val_acc: 1.0000
Epoch 8277/10000
100/100 [==============================] - 0s - loss: 3.5493e-08 - acc: 1.0000 - val_loss: 3.4259e-08 - val_acc: 1.0000
Epoch 8278/10000

100/100 [==============================] - 0s - loss: 3.9837e-08 - acc: 1.0000 - val_loss: 3.9996e-08 - val_acc: 1.0000
Epoch 8390/10000
100/100 [==============================] - 0s - loss: 3.8150e-08 - acc: 1.0000 - val_loss: 3.3437e-08 - val_acc: 1.0000
Epoch 8391/10000
100/100 [==============================] - 0s - loss: 3.3565e-08 - acc: 1.0000 - val_loss: 3.3019e-08 - val_acc: 1.0000
Epoch 8392/10000
100/100 [==============================] - 0s - loss: 3.8509e-08 - acc: 1.0000 - val_loss: 3.7187e-08 - val_acc: 1.0000
Epoch 8393/10000
100/100 [==============================] - 0s - loss: 3.6369e-08 - acc: 1.0000 - val_loss: 3.3006e-08 - val_acc: 1.0000
Epoch 8394/10000
100/100 [==============================] - 0s - loss: 3.4489e-08 - acc: 1.0000 - val_loss: 3.3379e-08 - val_acc: 1.0000
Epoch 8395/10000
100/100 [==============================] - 0s - loss: 3.3558e-08 - acc: 1.0000 - val_loss: 3.2852e-08 - val_acc: 1.0000
Epoch 8396/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 3.2787e-08 - acc: 1.0000 - val_loss: 3.1711e-08 - val_acc: 1.0000
Epoch 8508/10000
100/100 [==============================] - 0s - loss: 3.2076e-08 - acc: 1.0000 - val_loss: 3.1616e-08 - val_acc: 1.0000
Epoch 8509/10000
100/100 [==============================] - 0s - loss: 3.1525e-08 - acc: 1.0000 - val_loss: 3.1861e-08 - val_acc: 1.0000
Epoch 8510/10000
100/100 [==============================] - 0s - loss: 3.1863e-08 - acc: 1.0000 - val_loss: 3.2087e-08 - val_acc: 1.0000
Epoch 8511/10000
100/100 [==============================] - 0s - loss: 3.8839e-08 - acc: 1.0000 - val_loss: 4.0040e-08 - val_acc: 1.0000
Epoch 8512/10000
100/100 [==============================] - 0s - loss: 3.8760e-08 - acc: 1.0000 - val_loss: 3.4333e-08 - val_acc: 1.0000
Epoch 8513/10000
100/100 [==============================] - 0s - loss: 3.5934e-08 - acc: 1.0000 - val_loss: 3.4081e-08 - val_acc: 1.0000
Epoch 8514/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 3.5820e-08 - acc: 1.0000 - val_loss: 4.6555e-08 - val_acc: 1.0000
Epoch 8625/10000
100/100 [==============================] - 0s - loss: 4.0669e-08 - acc: 1.0000 - val_loss: 3.7402e-08 - val_acc: 1.0000
Epoch 8626/10000
100/100 [==============================] - 0s - loss: 3.5053e-08 - acc: 1.0000 - val_loss: 3.2922e-08 - val_acc: 1.0000
Epoch 8627/10000
100/100 [==============================] - 0s - loss: 3.4537e-08 - acc: 1.0000 - val_loss: 3.6270e-08 - val_acc: 1.0000
Epoch 8628/10000
100/100 [==============================] - 0s - loss: 3.7478e-08 - acc: 1.0000 - val_loss: 3.6784e-08 - val_acc: 1.0000
Epoch 8629/10000
100/100 [==============================] - 0s - loss: 3.8206e-08 - acc: 1.0000 - val_loss: 3.4894e-08 - val_acc: 1.0000
Epoch 8630/10000
100/100 [==============================] - 0s - loss: 4.2990e-08 - acc: 1.0000 - val_loss: 3.7394e-08 - val_acc: 1.0000
Epoch 8631/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 3.2898e-08 - acc: 1.0000 - val_loss: 3.0920e-08 - val_acc: 1.0000
Epoch 8743/10000
100/100 [==============================] - 0s - loss: 3.2878e-08 - acc: 1.0000 - val_loss: 3.3305e-08 - val_acc: 1.0000
Epoch 8744/10000
100/100 [==============================] - 0s - loss: 3.3853e-08 - acc: 1.0000 - val_loss: 3.3592e-08 - val_acc: 1.0000
Epoch 8745/10000
100/100 [==============================] - 0s - loss: 3.3821e-08 - acc: 1.0000 - val_loss: 3.3240e-08 - val_acc: 1.0000
Epoch 8746/10000
100/100 [==============================] - 0s - loss: 4.1400e-08 - acc: 1.0000 - val_loss: 4.2175e-08 - val_acc: 1.0000
Epoch 8747/10000
100/100 [==============================] - 0s - loss: 3.9354e-08 - acc: 1.0000 - val_loss: 3.2128e-08 - val_acc: 1.0000
Epoch 8748/10000
100/100 [==============================] - 0s - loss: 3.2514e-08 - acc: 1.0000 - val_loss: 3.1478e-08 - val_acc: 1.0000
Epoch 8749/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 3.9841e-08 - acc: 1.0000 - val_loss: 4.4294e-08 - val_acc: 1.0000
Epoch 8861/10000
100/100 [==============================] - 0s - loss: 4.2188e-08 - acc: 1.0000 - val_loss: 4.5122e-08 - val_acc: 1.0000
Epoch 8862/10000
100/100 [==============================] - 0s - loss: 4.3869e-08 - acc: 1.0000 - val_loss: 5.0896e-08 - val_acc: 1.0000
Epoch 8863/10000
100/100 [==============================] - 0s - loss: 4.8607e-08 - acc: 1.0000 - val_loss: 5.7821e-08 - val_acc: 1.0000
Epoch 8864/10000
100/100 [==============================] - 0s - loss: 4.7950e-08 - acc: 1.0000 - val_loss: 4.6494e-08 - val_acc: 1.0000
Epoch 8865/10000
100/100 [==============================] - 0s - loss: 4.0042e-08 - acc: 1.0000 - val_loss: 4.2478e-08 - val_acc: 1.0000
Epoch 8866/10000
100/100 [==============================] - 0s - loss: 3.7306e-08 - acc: 1.0000 - val_loss: 4.3731e-08 - val_acc: 1.0000
Epoch 8867/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 3.0347e-08 - acc: 1.0000 - val_loss: 3.2368e-08 - val_acc: 1.0000
Epoch 8978/10000
100/100 [==============================] - 0s - loss: 3.2785e-08 - acc: 1.0000 - val_loss: 2.8633e-08 - val_acc: 1.0000
Epoch 8979/10000
100/100 [==============================] - 0s - loss: 2.8712e-08 - acc: 1.0000 - val_loss: 2.9580e-08 - val_acc: 1.0000
Epoch 8980/10000
100/100 [==============================] - 0s - loss: 3.2650e-08 - acc: 1.0000 - val_loss: 2.9087e-08 - val_acc: 1.0000
Epoch 8981/10000
100/100 [==============================] - 0s - loss: 3.0977e-08 - acc: 1.0000 - val_loss: 3.0086e-08 - val_acc: 1.0000
Epoch 8982/10000
100/100 [==============================] - 0s - loss: 3.0759e-08 - acc: 1.0000 - val_loss: 2.9525e-08 - val_acc: 1.0000
Epoch 8983/10000
100/100 [==============================] - 0s - loss: 3.0139e-08 - acc: 1.0000 - val_loss: 2.9726e-08 - val_acc: 1.0000
Epoch 8984/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 3.1820e-08 - acc: 1.0000 - val_loss: 3.4129e-08 - val_acc: 1.0000
Epoch 9096/10000
100/100 [==============================] - 0s - loss: 3.5084e-08 - acc: 1.0000 - val_loss: 3.6746e-08 - val_acc: 1.0000
Epoch 9097/10000
100/100 [==============================] - 0s - loss: 3.9893e-08 - acc: 1.0000 - val_loss: 4.1394e-08 - val_acc: 1.0000
Epoch 9098/10000
100/100 [==============================] - 0s - loss: 4.8178e-08 - acc: 1.0000 - val_loss: 4.8981e-08 - val_acc: 1.0000
Epoch 9099/10000
100/100 [==============================] - 0s - loss: 4.7235e-08 - acc: 1.0000 - val_loss: 3.9219e-08 - val_acc: 1.0000
Epoch 9100/10000
100/100 [==============================] - 0s - loss: 3.9107e-08 - acc: 1.0000 - val_loss: 3.2782e-08 - val_acc: 1.0000
Epoch 9101/10000
100/100 [==============================] - 0s - loss: 3.5861e-08 - acc: 1.0000 - val_loss: 3.1753e-08 - val_acc: 1.0000
Epoch 9102/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 3.4739e-08 - acc: 1.0000 - val_loss: 4.0572e-08 - val_acc: 1.0000
Epoch 9214/10000
100/100 [==============================] - 0s - loss: 4.1225e-08 - acc: 1.0000 - val_loss: 3.2620e-08 - val_acc: 1.0000
Epoch 9215/10000
100/100 [==============================] - 0s - loss: 2.9452e-08 - acc: 1.0000 - val_loss: 3.6103e-08 - val_acc: 1.0000
Epoch 9216/10000
100/100 [==============================] - 0s - loss: 3.1045e-08 - acc: 1.0000 - val_loss: 3.7733e-08 - val_acc: 1.0000
Epoch 9217/10000
100/100 [==============================] - 0s - loss: 3.2576e-08 - acc: 1.0000 - val_loss: 4.2110e-08 - val_acc: 1.0000
Epoch 9218/10000
100/100 [==============================] - 0s - loss: 3.6579e-08 - acc: 1.0000 - val_loss: 3.4207e-08 - val_acc: 1.0000
Epoch 9219/10000
100/100 [==============================] - 0s - loss: 3.2909e-08 - acc: 1.0000 - val_loss: 3.6818e-08 - val_acc: 1.0000
Epoch 9220/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 3.1893e-08 - acc: 1.0000 - val_loss: 2.7392e-08 - val_acc: 1.0000
Epoch 9332/10000
100/100 [==============================] - ETA: 0s - loss: 2.8396e-08 - acc: 1.000 - 0s - loss: 3.3294e-08 - acc: 1.0000 - val_loss: 2.7658e-08 - val_acc: 1.0000
Epoch 9333/10000
100/100 [==============================] - 0s - loss: 3.3467e-08 - acc: 1.0000 - val_loss: 2.7860e-08 - val_acc: 1.0000
Epoch 9334/10000
100/100 [==============================] - 0s - loss: 3.9725e-08 - acc: 1.0000 - val_loss: 2.7400e-08 - val_acc: 1.0000
Epoch 9335/10000
100/100 [==============================] - 0s - loss: 3.3981e-08 - acc: 1.0000 - val_loss: 2.7661e-08 - val_acc: 1.0000
Epoch 9336/10000
100/100 [==============================] - 0s - loss: 3.2263e-08 - acc: 1.0000 - val_loss: 2.7889e-08 - val_acc: 1.0000
Epoch 9337/10000
100/100 [==============================] - 0s - loss: 2.7241e-08 - acc: 1.0000 - val_loss: 3.1344e-08 - val_acc: 1.0000
Epoch 9338/10000

100/100 [==============================] - 0s - loss: 2.9187e-08 - acc: 1.0000 - val_loss: 2.8910e-08 - val_acc: 1.0000
Epoch 9450/10000
100/100 [==============================] - 0s - loss: 2.7850e-08 - acc: 1.0000 - val_loss: 2.9844e-08 - val_acc: 1.0000
Epoch 9451/10000
100/100 [==============================] - 0s - loss: 3.1570e-08 - acc: 1.0000 - val_loss: 2.7392e-08 - val_acc: 1.0000
Epoch 9452/10000
100/100 [==============================] - 0s - loss: 2.6730e-08 - acc: 1.0000 - val_loss: 2.8913e-08 - val_acc: 1.0000
Epoch 9453/10000
100/100 [==============================] - 0s - loss: 2.7134e-08 - acc: 1.0000 - val_loss: 3.0776e-08 - val_acc: 1.0000
Epoch 9454/10000
100/100 [==============================] - 0s - loss: 2.8793e-08 - acc: 1.0000 - val_loss: 2.9925e-08 - val_acc: 1.0000
Epoch 9455/10000
100/100 [==============================] - 0s - loss: 2.9174e-08 - acc: 1.0000 - val_loss: 2.7441e-08 - val_acc: 1.0000
Epoch 9456/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 3.0106e-08 - acc: 1.0000 - val_loss: 2.6825e-08 - val_acc: 1.0000
Epoch 9568/10000
100/100 [==============================] - 0s - loss: 2.8026e-08 - acc: 1.0000 - val_loss: 2.6262e-08 - val_acc: 1.0000
Epoch 9569/10000
100/100 [==============================] - 0s - loss: 2.6458e-08 - acc: 1.0000 - val_loss: 2.6671e-08 - val_acc: 1.0000
Epoch 9570/10000
100/100 [==============================] - 0s - loss: 2.7299e-08 - acc: 1.0000 - val_loss: 2.6101e-08 - val_acc: 1.0000
Epoch 9571/10000
100/100 [==============================] - 0s - loss: 3.2859e-08 - acc: 1.0000 - val_loss: 2.8370e-08 - val_acc: 1.0000
Epoch 9572/10000
100/100 [==============================] - 0s - loss: 2.9628e-08 - acc: 1.0000 - val_loss: 2.6812e-08 - val_acc: 1.0000
Epoch 9573/10000
100/100 [==============================] - 0s - loss: 2.7688e-08 - acc: 1.0000 - val_loss: 2.6140e-08 - val_acc: 1.0000
Epoch 9574/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 2.6755e-08 - acc: 1.0000 - val_loss: 2.6099e-08 - val_acc: 1.0000
Epoch 9686/10000
100/100 [==============================] - 0s - loss: 2.6253e-08 - acc: 1.0000 - val_loss: 2.6031e-08 - val_acc: 1.0000
Epoch 9687/10000
100/100 [==============================] - 0s - loss: 2.6121e-08 - acc: 1.0000 - val_loss: 2.6059e-08 - val_acc: 1.0000
Epoch 9688/10000
100/100 [==============================] - 0s - loss: 2.6299e-08 - acc: 1.0000 - val_loss: 2.6147e-08 - val_acc: 1.0000
Epoch 9689/10000
100/100 [==============================] - 0s - loss: 2.7141e-08 - acc: 1.0000 - val_loss: 2.6663e-08 - val_acc: 1.0000
Epoch 9690/10000
100/100 [==============================] - 0s - loss: 2.7455e-08 - acc: 1.0000 - val_loss: 2.6431e-08 - val_acc: 1.0000
Epoch 9691/10000
100/100 [==============================] - 0s - loss: 2.8039e-08 - acc: 1.0000 - val_loss: 2.6516e-08 - val_acc: 1.0000
Epoch 9692/10000
100/100 [==============================] 

100/100 [==============================] - 0s - loss: 2.6636e-08 - acc: 1.0000 - val_loss: 2.5173e-08 - val_acc: 1.0000
Epoch 9804/10000
100/100 [==============================] - 0s - loss: 2.5229e-08 - acc: 1.0000 - val_loss: 2.5277e-08 - val_acc: 1.0000
Epoch 9805/10000
100/100 [==============================] - 0s - loss: 2.5413e-08 - acc: 1.0000 - val_loss: 2.5279e-08 - val_acc: 1.0000
Epoch 9806/10000
100/100 [==============================] - ETA: 0s - loss: 2.6504e-08 - acc: 1.000 - 0s - loss: 2.6673e-08 - acc: 1.0000 - val_loss: 2.6640e-08 - val_acc: 1.0000
Epoch 9807/10000
100/100 [==============================] - 0s - loss: 2.6689e-08 - acc: 1.0000 - val_loss: 2.6173e-08 - val_acc: 1.0000
Epoch 9808/10000
100/100 [==============================] - 0s - loss: 2.6924e-08 - acc: 1.0000 - val_loss: 2.6092e-08 - val_acc: 1.0000
Epoch 9809/10000
100/100 [==============================] - 0s - loss: 2.8810e-08 - acc: 1.0000 - val_loss: 2.7973e-08 - val_acc: 1.0000
Epoch 9810/10000

100/100 [==============================] - 0s - loss: 3.0576e-08 - acc: 1.0000 - val_loss: 2.5629e-08 - val_acc: 1.0000
Epoch 9922/10000
100/100 [==============================] - 0s - loss: 2.6475e-08 - acc: 1.0000 - val_loss: 2.5069e-08 - val_acc: 1.0000
Epoch 9923/10000
100/100 [==============================] - 0s - loss: 2.6632e-08 - acc: 1.0000 - val_loss: 2.4853e-08 - val_acc: 1.0000
Epoch 9924/10000
100/100 [==============================] - 0s - loss: 2.4919e-08 - acc: 1.0000 - val_loss: 2.5644e-08 - val_acc: 1.0000
Epoch 9925/10000
100/100 [==============================] - 0s - loss: 2.5198e-08 - acc: 1.0000 - val_loss: 2.6074e-08 - val_acc: 1.0000
Epoch 9926/10000
100/100 [==============================] - 0s - loss: 2.6409e-08 - acc: 1.0000 - val_loss: 3.2245e-08 - val_acc: 1.0000
Epoch 9927/10000
100/100 [==============================] - 0s - loss: 2.9824e-08 - acc: 1.0000 - val_loss: 3.2866e-08 - val_acc: 1.0000
Epoch 9928/10000
100/100 [==============================] 

In [17]:
predict = model.predict(data)

In [18]:
print(predict)

[[[   0.99395508    1.98522842    2.99932957    4.01930237    4.9934864
      5.9774518     6.99177027    8.00243664    8.99053574    9.98281384
     10.99869823   12.01511955   12.99868393   13.99233627   15.02353764
     16.00413132   17.00183296   18.00247765   19.00620079   19.97957611
     20.99639511   22.00535965   23.03126907   23.99457932   25.0073967
     25.98711395   26.98984528   27.98152733   28.97661591   29.97803879
     30.99940681   32.00864029   32.99717331   33.99354172   34.98986435
     35.99935913   36.98899078   37.99792099   39.01105881   40.02589798
     41.00576401   42.01037979   43.00629807   43.98942184   45.00488663
     45.99213791   46.99948883   47.99733734   48.99403763   50.01021576
     51.00231552   51.98408127   52.99483871   53.98939896   54.99875641
     56.0211525    56.99502563   57.99056244   58.98592758   59.99246216
     61.01183319   62.00353622   62.98943329   64.02242279   65.01579285
     65.99591827   67.00032043   67.99795532   68.998