In [2]:
#!conda install --name root scikit-learn -y

In [3]:
#!conda install --name root -c conda-forge tensorflow -y

In [4]:
#!conda install --name root keras -y

In [5]:
import numpy as np

from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM

Using TensorFlow backend.


In [6]:
leng=4

data = [[i+j for j in range(leng)] for i in range(100)]
data = np.array(data, dtype=np.float32)
target = [[i+j+1 for j in range(leng)] for i in range(100)]
target = np.array(target, dtype=np.float32)
print(data[:10])
print(target[:10])
data = data.reshape(100, 1, leng)/200
target = target.reshape(100,1,leng)/200

[[  0.   1.   2.   3.]
 [  1.   2.   3.   4.]
 [  2.   3.   4.   5.]
 [  3.   4.   5.   6.]
 [  4.   5.   6.   7.]
 [  5.   6.   7.   8.]
 [  6.   7.   8.   9.]
 [  7.   8.   9.  10.]
 [  8.   9.  10.  11.]
 [  9.  10.  11.  12.]]
[[  1.   2.   3.   4.]
 [  2.   3.   4.   5.]
 [  3.   4.   5.   6.]
 [  4.   5.   6.   7.]
 [  5.   6.   7.   8.]
 [  6.   7.   8.   9.]
 [  7.   8.   9.  10.]
 [  8.   9.  10.  11.]
 [  9.  10.  11.  12.]
 [ 10.  11.  12.  13.]]


In [7]:

model = Sequential()  
model.add(LSTM(leng, input_shape=(1, leng),return_sequences=True,activation='sigmoid'))
model.add(LSTM(leng, input_shape=(1, leng),return_sequences=True,activation='sigmoid'))
model.add(LSTM(leng, input_shape=(1, leng),return_sequences=True,activation='sigmoid'))
model.add(LSTM(leng, input_shape=(1, leng),return_sequences=True,activation='sigmoid'))
model.add(LSTM(leng, input_shape=(1, leng),return_sequences=True,activation='sigmoid'))
model.add(LSTM(leng, input_shape=(1, leng),return_sequences=True,activation='sigmoid'))

In [8]:
model.compile(loss='mse', optimizer='adam',metrics=['accuracy'])
model.fit(data, target, epochs=10000, batch_size=50,validation_data=(data,target))

Train on 100 samples, validate on 100 samples
Epoch 1/10000
100/100 [==============================] - 12s 120ms/step - loss: 0.0226 - acc: 0.0000e+00 - val_loss: 0.0226 - val_acc: 0.0000e+00
Epoch 2/10000
100/100 [==============================] - 0s 326us/step - loss: 0.0226 - acc: 0.0000e+00 - val_loss: 0.0226 - val_acc: 0.0000e+00
Epoch 3/10000
100/100 [==============================] - 0s 266us/step - loss: 0.0226 - acc: 0.0000e+00 - val_loss: 0.0225 - val_acc: 0.0000e+00
Epoch 4/10000
100/100 [==============================] - 0s 231us/step - loss: 0.0225 - acc: 0.0000e+00 - val_loss: 0.0225 - val_acc: 0.0000e+00
Epoch 5/10000
100/100 [==============================] - 0s 466us/step - loss: 0.0225 - acc: 0.0000e+00 - val_loss: 0.0225 - val_acc: 0.0000e+00
Epoch 6/10000
100/100 [========================

In [9]:
predict = model.predict(data)

In [10]:
print(predict)

[[[ 0.00566523  0.0106875   0.0156572   0.02056956]]

 [[ 0.01030049  0.01531675  0.02029205  0.02522101]]

 [[ 0.0150617   0.02007257  0.02505314  0.02999782]]

 [[ 0.01995375  0.02495977  0.02994533  0.03490477]]

 [[ 0.0249174   0.02991925  0.0349094   0.03988243]]

 [[ 0.02998723  0.03498552  0.0399799   0.04496539]]

 [[ 0.03510073  0.04009612  0.04509427  0.05009089]]

 [[ 0.0400445   0.04503766  0.05003902  0.05504511]]

 [[ 0.04489136  0.0498828   0.05488694  0.05990113]]

 [[ 0.04980069  0.0547909   0.0597974   0.06481861]]

 [[ 0.05477202  0.05976143  0.06476995  0.06979714]]

 [[ 0.0598047   0.06479362  0.06980385  0.07483599]]

 [[ 0.06489763  0.06988646  0.07489803  0.07993414]]

 [[ 0.07004967  0.07503869  0.08005127  0.08509032]]

 [[ 0.07525915  0.08024865  0.08526191  0.090303  ]]

 [[ 0.08052438  0.08551457  0.09052823  0.09557047]]

 [[ 0.08584318  0.09083422  0.09584803  0.10089054]]

 [[ 0.09066191  0.09565389  0.10066766  0.10570968]]

 [[ 0.0954807   0.10047362  